export const orders = [
    {
        "OrderID": "2673754",
        "DepartmentID": 10,
        "OrderNumber": "21994253",
        "SubmissionNumber": "10376339",
        "DateReceived": "11/02/20",
        "DateArrived": "11/02/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Processing",
        "Status": 3,
        "ItemCount": 43,
        "Service": "Preferred 20 Day \u003c 500",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    },
    {
        "OrderID": "2673741",
        "DepartmentID": 10,
        "OrderNumber": "21994240",
        "SubmissionNumber": "10376392",
        "DateReceived": "11/02/20",
        "DateArrived": "11/02/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Processing",
        "Status": 3,
        "ItemCount": 70,
        "Service": "Preferred 20 Day \u003c 500",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    },
    {
        "OrderID": "2673597",
        "DepartmentID": 10,
        "OrderNumber": "21994096",
        "SubmissionNumber": "10369218",
        "DateReceived": "11/02/20",
        "DateArrived": "11/02/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Processing",
        "Status": 3,
        "ItemCount": 75,
        "Service": "Preferred 20 Day \u003c 500",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    },
    {
        "OrderID": "2673593",
        "DepartmentID": 10,
        "OrderNumber": "21994092",
        "SubmissionNumber": "10374764",
        "DateReceived": "11/02/20",
        "DateArrived": "11/02/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Processing",
        "Status": 3,
        "ItemCount": 85,
        "Service": "Preferred 20 Day \u003c 500",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    },
    {
        "OrderID": "2673572",
        "DepartmentID": 10,
        "OrderNumber": "21994071",
        "SubmissionNumber": "10369279",
        "DateReceived": "11/02/20",
        "DateArrived": "11/02/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Processing",
        "Status": 3,
        "ItemCount": 78,
        "Service": "Preferred 20 Day \u003c 500",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    },
    {
        "OrderID": "2673549",
        "DepartmentID": 10,
        "OrderNumber": "21994048",
        "SubmissionNumber": "10369471",
        "DateReceived": "11/02/20",
        "DateArrived": "11/02/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Processing",
        "Status": 3,
        "ItemCount": 101,
        "Service": "Preferred 20 Day \u003c 500",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    },
    {
        "OrderID": "2650003",
        "DepartmentID": 10,
        "OrderNumber": "21970421",
        "SubmissionNumber": "10358064",
        "DateReceived": "10/15/20",
        "DateArrived": "10/14/20",
        "ShippedDate": "\/Date(1603436400000)\/",
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "10/23/20",
        "OrderStatus": "Shipped",
        "Status": 4,
        "ItemCount": 1,
        "Service": "Preferred 5 Day \u003c 2499",
        "Department": "PSA",
        "CertsReady": true,
        "Carrier": "USPS",
        "TrackingNumber": "9210890163776905084416"
    },
    {
        "OrderID": null,
        "DepartmentID": 10,
        "OrderNumber": null,
        "SubmissionNumber": "10345941",
        "DateReceived": null,
        "DateArrived": "10/08/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Arrived",
        "Status": 1,
        "ItemCount": 80,
        "Service": "Preferred Ultra-Modern (2017 and newer)",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    },
    {
        "OrderID": null,
        "DepartmentID": 10,
        "OrderNumber": null,
        "SubmissionNumber": "10345945",
        "DateReceived": null,
        "DateArrived": "10/08/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Arrived",
        "Status": 1,
        "ItemCount": 80,
        "Service": "Preferred Ultra-Modern (2017 and newer)",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    },
    {
        "OrderID": null,
        "DepartmentID": 10,
        "OrderNumber": null,
        "SubmissionNumber": "10345949",
        "DateReceived": null,
        "DateArrived": "10/08/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Arrived",
        "Status": 1,
        "ItemCount": 86,
        "Service": "Preferred Modern (1972-2016)",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    },
    {
        "OrderID": null,
        "DepartmentID": 10,
        "OrderNumber": null,
        "SubmissionNumber": "10353922",
        "DateReceived": null,
        "DateArrived": "10/08/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Arrived",
        "Status": 1,
        "ItemCount": 264,
        "Service": "Preferred Ultra-Modern (2017 and newer)",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    },
    {
        "OrderID": "2676602",
        "DepartmentID": 10,
        "OrderNumber": "21997040",
        "SubmissionNumber": "10345950",
        "DateReceived": "11/04/20",
        "DateArrived": "10/07/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Processing",
        "Status": 3,
        "ItemCount": 11,
        "Service": "Preferred Dual \u003c 100",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    },
    {
        "OrderID": "2676578",
        "DepartmentID": 10,
        "OrderNumber": "21997016",
        "SubmissionNumber": "10354064",
        "DateReceived": "11/04/20",
        "DateArrived": "10/07/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Processing",
        "Status": 3,
        "ItemCount": 93,
        "Service": "Preferred 20 Day \u003c 500",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    },
    {
        "OrderID": "2676477",
        "DepartmentID": 10,
        "OrderNumber": "21996915",
        "SubmissionNumber": "10344734",
        "DateReceived": "11/04/20",
        "DateArrived": "10/07/20",
        "ShippedDate": null,
        "HasOnlineSubmissionNumber": true,
        "DateShipped": "N/A",
        "OrderStatus": "Processing",
        "Status": 3,
        "ItemCount": 50,
        "Service": "Preferred - Modern",
        "Department": "PSA",
        "CertsReady": false,
        "Carrier": "None",
        "TrackingNumber": ""
    }
]